<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::create('categories', function (Blueprint $table) { $table->id(); $table->string('name'); $table->string('slug')->unique(); $table->string('image_url')->nullable(); $table->boolean('is_active')->default(true); $table->unsignedInteger('sort_order')->default(0); $table->timestamps(); });
        Schema::create('menu_items', function (Blueprint $table) { $table->id(); $table->foreignId('category_id')->constrained()->cascadeOnDelete(); $table->string('name'); $table->string('slug')->unique(); $table->text('description')->nullable(); $table->unsignedBigInteger('price'); $table->unsignedBigInteger('sale_price')->nullable(); $table->string('image_url')->nullable(); $table->json('tags')->nullable(); $table->json('allergens')->nullable(); $table->unsignedInteger('prep_minutes')->default(15); $table->boolean('is_available')->default(true); $table->boolean('is_featured')->default(false); $table->timestamps(); });
        Schema::create('tables', function (Blueprint $table) { $table->id(); $table->string('name'); $table->string('hall')->default('سالن اصلی'); $table->unsignedSmallInteger('capacity'); $table->string('status')->default('available'); $table->string('qr_token')->unique(); $table->timestamps(); });
        Schema::create('customers', function (Blueprint $table) { $table->id(); $table->string('name'); $table->string('phone')->unique(); $table->string('email')->nullable(); $table->date('birthday')->nullable(); $table->unsignedInteger('loyalty_points')->default(0); $table->timestamps(); });
        Schema::create('reservations', function (Blueprint $table) { $table->id(); $table->foreignId('customer_id')->nullable()->constrained()->nullOnDelete(); $table->foreignId('table_id')->nullable()->constrained()->nullOnDelete(); $table->string('type')->default('table'); $table->date('date'); $table->time('time'); $table->unsignedSmallInteger('guests'); $table->string('status')->default('pending'); $table->string('package')->nullable(); $table->unsignedBigInteger('deposit')->default(0); $table->text('notes')->nullable(); $table->timestamps(); });
        Schema::create('orders', function (Blueprint $table) { $table->id(); $table->foreignId('customer_id')->nullable()->constrained()->nullOnDelete(); $table->foreignId('table_id')->nullable()->constrained()->nullOnDelete(); $table->string('channel')->default('delivery'); $table->string('status')->default('new'); $table->string('payment_status')->default('unpaid'); $table->unsignedBigInteger('subtotal')->default(0); $table->unsignedBigInteger('delivery_fee')->default(0); $table->unsignedBigInteger('tax')->default(0); $table->unsignedBigInteger('total')->default(0); $table->text('address')->nullable(); $table->text('notes')->nullable(); $table->timestamps(); });
        Schema::create('order_items', function (Blueprint $table) { $table->id(); $table->foreignId('order_id')->constrained()->cascadeOnDelete(); $table->foreignId('menu_item_id')->constrained()->restrictOnDelete(); $table->unsignedSmallInteger('quantity'); $table->unsignedBigInteger('unit_price'); $table->json('options')->nullable(); $table->timestamps(); });
        Schema::create('delivery_zones', function (Blueprint $table) { $table->id(); $table->string('name'); $table->unsignedBigInteger('fee')->default(0); $table->unsignedBigInteger('free_over')->nullable(); $table->unsignedSmallInteger('eta_minutes')->default(45); $table->boolean('is_active')->default(true); $table->timestamps(); });
        Schema::create('gallery_items', function (Blueprint $table) { $table->id(); $table->string('title'); $table->string('type')->default('space'); $table->string('image_url'); $table->text('caption')->nullable(); $table->boolean('is_featured')->default(false); $table->unsignedInteger('sort_order')->default(0); $table->timestamps(); });
        Schema::create('event_packages', function (Blueprint $table) { $table->id(); $table->string('name'); $table->text('description')->nullable(); $table->unsignedBigInteger('price_from')->default(0); $table->unsignedSmallInteger('min_guests')->default(6); $table->unsignedSmallInteger('max_guests')->default(40); $table->string('image_url')->nullable(); $table->json('features')->nullable(); $table->boolean('is_active')->default(true); $table->timestamps(); });
    }
    public function down(): void { Schema::dropIfExists('event_packages'); Schema::dropIfExists('gallery_items'); Schema::dropIfExists('order_items'); Schema::dropIfExists('orders'); Schema::dropIfExists('reservations'); Schema::dropIfExists('customers'); Schema::dropIfExists('tables'); Schema::dropIfExists('menu_items'); Schema::dropIfExists('categories'); Schema::dropIfExists('delivery_zones'); }
};
